### ISSUE TITLE
High pass filter with golang question

### ISSUE THREAD

**Issue by boksili** [jamestunnell/go-dsp#1]
HI.
I am new in golang.

I want open file and do HPF and save the file after HPF.

the file format is
1 28.00000
2 29.00000
3 28.00000
4 30.00000
5 28.00000
.....
.....

it has two column
(time well_height)

the sample rate is 0.0166Hz (60 seconds interval well height recording)
It has very very long term noise more than 200 sec
So I want to High pass filter with cutoff frequency 0.005 Hz

I looked over your golang code very carefully with 1 week
but Still I failed with your code.

Is there any sample form with open file and do HPF and save to file with HPF results ?

please help me. I am graduate course student.

Thanks for all.

TaeRhee

**Comment by jamestunnell** [comment]
Which part are you having trouble with, reading/writing the file or running the HPF?

**Comment by boksili** [comment]
Actually, It was difficult for running the HPF part.
The exact grammer was mystery part.

**Comment by jamestunnell** [comment]
Are you trying to use an IIR or FIR filter?

**Comment by boksili** [comment]
I am trying to do FIR filter as well.

**Comment by boksili** [comment]
This is the un-completed code trouble with.
I do a lot of test with several code.

-----------------------------
package main

import (
				"fmt"
				"github.com/eripe970/go-dsp-utils"
				"github.com/go-echarts/go-echarts/v2/charts"
				"github.com/go-echarts/go-echarts/v2/components"
				"github.com/go-echarts/go-echarts/v2/opts"
				"github.com/go-echarts/go-echarts/v2/types"
				"log"
				"net/http"
				"time"
				"github.com/mattetti/audio"
				"github.com/mattetti/audio/transforms/filters"
)

func main() {
		 http.HandleFunc("/", handler)
		 log.Fatal(http.ListenAndServe(":4000", nil))
}

func	handler(w http.ResponseWriter, _ *http.Request) {
				signal, _ := dsp.ReadSignalFile("examples/signals/tidal_sample_part.txt", 0.0166)
				
				plot1 := plotSignal(signal, opts.Title{
								Title:    "Original signal 60sec per 1 measure, Well-Height",
								Subtitle: signal.String(),
				})
				signalday := signal.Sample(86400 * time.Second)

				page := components.NewPage()
				page.AddCharts(
					plot1,
		
				)

				page.Render(w)
}

						
func (s *signal) HighPassFilter(curOffFreq float64) (*signal, error) {
		   buffer := audio.NewPCMFloatBuffer(s.Signal), &audio.Format{SampleRate: int(s.SampleRate)})
		   
		   err := filters.HighPass(buffer, cutOffFreq)

			if err != nil {
				return nil, err
			}

			return &Signal{
					SampleRate: s.SampleRate,
					Signal:     buffer.Floats,
			}, nil
}


func plotSignal(signal *dsp.Signal, title opts.Title) *charts.Line {
	// B-1. func plotSignal 로 된 그래프의 그림형태를 지정하는 부분, func plotSignal 에만 해당
	x := make([]string, 0)
	y := make([]opts.LineData, 0)
	for i := 0; i < signal.Length(); i++ {
		x = append(x, fmt.Sprintf("%.3f", float64(i)/signal.SampleRate))
		y = append(y, opts.LineData{Value: signal.Signal[i], Symbol: "none"})
	}

	line := charts.NewLine()
	line.SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{Theme: types.ThemeWonderland}),
		charts.WithYAxisOpts(opts.YAxis{Max: signal.Max(), Min: signal.Min(), SplitNumber: 10}),
		charts.WithXAxisOpts(opts.XAxis{SplitNumber: 10}),
		charts.WithTitleOpts(title))

	line.SetXAxis(x).AddSeries("data", y).SetSeriesOptions(
		charts.WithLineChartOpts(opts.LineChart{
			Smooth: true,
		}),
	)

	return line
}
------------------------------------

**Comment by jamestunnell** [comment]
I don’t see my go-dsp library being used there at all…

**Comment by boksili** [comment]
Thanks for the help.
